spring.application.name=ReceiptUpload

# //*********************개발용 설정***********************//
# 데이터베이스 연결 설정
# 재윤 선임 local PC
#spring.datasource.url=jdbc:postgresql://10.10.103.85:5432/postgres
# SERVER PC - PROD
spring.datasource.url=jdbc:postgresql://10.10.102.10:5434/postgres
# SERVER PC - DEV
#spring.datasource.url=jdbc:postgresql://10.10.102.10:5435/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 서버 포트 설정
server.port=8083

# 로깅 설정
logging.level.com.daeyang.ReceiptUpload=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate=DEBUG

# 체크시트 이미지 저장 경로
storage.base-path=\\\\10.10.102.10\\checkSheetIMG

# //************************끝**************************//

# //*********************배포용 설정***********************//
# 데이터베이스 연결 설정
# SERVER PC - PROD
#spring.datasource.url=jdbc:postgresql://10.10.102.10:5434/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

# 서버 포트 설정
#server.port=8082

# 로깅 설정
#logging.level.com.daeyang.ReceiptUpload=INFO
#logging.level.org.springframework.jdbc.core=INFO
#logging.level.org.springframework.jdbc.core.JdbcTemplate=INFO
#logging.level.org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate=INFO

# 체크시트 이미지 저장 경로
#storage.base-path=D:/checkSheetIMG

# //************************끝**************************//

# //************************공용 설정**************************//
# 활성 로그 파일 경로 (현재 파일)
logging.file.name=D:/ReceiptUploadLog/smart-factory-web.log
# 날짜별(+ 사이즈별) 롤링 파일 네이밍
logging.logback.rollingpolicy.file-name-pattern=D:/ReceiptUploadLog/smart-factory-web-%d{yyyy-MM-dd}.%i.log
# 한 조각 최대 파일 크기
logging.logback.rollingpolicy.max-file-size=50MB
# 보관 일수
logging.logback.rollingpolicy.max-history=40
# 전체 디스크 사용 상한
#logging.logback.rollingpolicy.total-size-cap=10GB
# 앱 시작 시 오래된 파일 정리
#logging.logback.rollingpolicy.clean-history-on-start=true

#소스 저장 시 재실행 방지
spring.devtools.restart.enabled=false

# --- MSSQL(커스텀 접두어) ---
# trustServerCertificate=true => MSSQL Server 인증서 사용하지 않음 (25.09.18 from.김도훈 팀장님) => 인증서 검사 우회
app.datasource.mssql.url=jdbc:sqlserver://210.223.182.4:1433;encrypt=true;trustServerCertificate=true;
app.datasource.mssql.username=smartuser
app.datasource.mssql.password=plc2025@
app.datasource.mssql.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.mssql.hikari.maximum-pool-size=10
app.datasource.mssql.hikari.minimum-idle=2
app.datasource.mssql.hikari.connection-timeout=30000
app.datasource.mssql.hikari.idle-timeout=480000
app.datasource.mssql.hikari.max-lifetime=600000

# --- PostgreSQL Hikari 설정 ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=180000
spring.datasource.hikari.idle-timeout=480000
spring.datasource.hikari.max-lifetime=600000

